# MythicKeysPlugin
# Made by Aria Sangarin

# Config Version 2

# Whether or not the event should be fired
# if a command was configured for the key ID.
run_event_on_command: true

# Input your desired keys here and the client mod
# will automatically grab these from the server and
# allow the player to use, see and customize them.
Keys:
    example_key: # Purely for organization. Can be named anything.
        Id: "myserver:mycoolkey" # The namespace and path of the pressed key which is passed to the event
        Name: "Example Key" # The name of this keybinding as displayed in the settings
        Category: "Example Category" # The category this key falls under in the settings
        DefaultKey: 74 # The default keybinding to use. See https://www.glfw.org/docs/latest/group__keys.html (74 is J)
        RunCommand: "say %player%, you just pressed the example key!" # The command to run. You can use '%player%' as a placeholder.
        # There is also support for all PAPI placeholders.
        # If you don't want the key to run a command (for external plugin support), just leave it empty.
    another_key:
        Id: examplekeytwo # A key without a namespace will simply use the default namespace.
        #This example ID will become: "mythickeysplugin:examplekeytwo"
        Name: "Another Key"
        Category: "Example Category"
        DefaultKey: 77 # 77 is the M key
        RunCommand: "!msg %player% You pressed another example key. Nice."
        # Putting a ! as the first letter of the command will make it run from console.